name    'stbenjam-stbenjam'
version '0.4.1'
author  'stbenjam'
license 'MIT'
summary 'Configures a box to my liking'
description 'Configures a box to my liking'
project_page 'https://github.com/stbenjam/puppet-stbenjam'

dependency 'puppetlabs/stdlib', '>= 3.0.0'
dependency 'theforeman/git', '>= 1.3.0'
