export ZSH=$HOME/.oh-my-zsh

# Smiley prompt
RPROMPT='%(?,%F{green}:%),%F{yellow}%? %F{red}:()%f'

# Oh my ZSH settings
ZSH_THEME="gentoo"
DISABLE_AUTO_UPDATE="true"
plugins=(git)
source $ZSH/oh-my-zsh.sh

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/stbenjam/.local/bin:/home/stbenjam/bin"
export LANG=en_US.UTF-8
export EDITOR='vim'
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
export GPG_TTY=$(tty)

PERL_MB_OPT="--install_base \"/home/stbenjam/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/stbenjam/perl5"; export PERL_MM_OPT;

# some helpful aliases
alias -g G='|grep'
alias grep="grep --color=auto"
alias -g L='|less'
alias -g T='|tail'
alias -g V='|vim'

alias ws="python -m SimpleHTTPServer"
alias dj="python manage.py runserver"
alias rs="rails s"


# ls on cd
function chpwd() {
    emulate -LR zsh
        ls
}

function dsh() {
    sed -i ${1}d ~/.ssh/known_hosts
}

